apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: java-simple-app-prd
  namespace: microservice
spec:
  maxReplicas: MAX_REPLICAS
  minReplicas: MIN_REPLICAS
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: java-simple-app-prd
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60
